{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmo.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dmo.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  selector:
    {{- include "dmo.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
{{- end }}
